import Head from 'next/head'
import Header from '../components/Header'
import PostPreview from '../components/post-preview'
import type { NextPage, GetStaticProps } from 'next'
import { IPOST } from '../types/post'
import Link from 'next/link'
import { getAllPosts } from '../utils/mdxUtils'

type Props = {
  posts: IPOST[]
}

const Home = ({ posts }: Props) => {

  return (
    <div className="">
      <Head>
        <title>MattScript</title>
        <meta name="description" content="Generated by create next app" />        
      </Head>

      <main className=''>
        
              
              <h1>Technical Articles</h1>
              <div>
                {
                  posts.map((post) => (

                    <PostPreview key={post.slug} title={post.title} thumbnail={post.thumbnail} date={post.date} slug={post.slug} description={post.description} />
                  ))
                  
                }
              </div>
      </main>

      
    </div>
  )
}
export default Home

export const getStaticProps: GetStaticProps = async () => {
  const posts = getAllPosts([
    'title',
    'slug',
    'date',
    'description',
    'thumbnail'
  ]);
  return { props: { posts } }
}